"""initial_schema

Revision ID: 4559fccc883a
Revises: 
Create Date: 2026-05-16 10:01:29.221234

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '4559fccc883a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
