"""add_rotation_day_v4_fields

Revision ID: 7775dfc07ada
Revises: 4559fccc883a
Create Date: 2026-05-16 11:10:24.286076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7775dfc07ada'
down_revision: Union[str, Sequence[str], None] = '4559fccc883a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rotation_days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('morning_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('warm_up_min', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('upper_back_core_min', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('secondary_min', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cool_down_min', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('total_min', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('fits_60', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('priority_exercises', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('secondary_exercises', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('week_rule', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rotation_days', schema=None) as batch_op:
        batch_op.drop_column('week_rule')
        batch_op.drop_column('secondary_exercises')
        batch_op.drop_column('priority_exercises')
        batch_op.drop_column('fits_60')
        batch_op.drop_column('total_min')
        batch_op.drop_column('cool_down_min')
        batch_op.drop_column('secondary_min')
        batch_op.drop_column('upper_back_core_min')
        batch_op.drop_column('warm_up_min')
        batch_op.drop_column('morning_time')

    # ### end Alembic commands ###
