"""add_plan_json_to_plan

Revision ID: 930832d8e721
Revises: 7775dfc07ada
Create Date: 2026-05-16 13:21:56.495010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '930832d8e721'
down_revision: Union[str, Sequence[str], None] = '7775dfc07ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('plan_json')

    # ### end Alembic commands ###
